# Site settings
title: "Volt"
description: > # this means to ignore newlines until "baseurl:"
  Volt Programing Language
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.volt-lang.org" # the base hostname & protocol for your site
twitter_username:
github_username: VoltLang

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
